name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  ARTIFACTORY_REPOSITORY: 'NU4260001_ProcessDataEtlResults_Lambda'

trigger:
  branches:
    include:
      - trunk
      - feature/*
  paths:
    include:
      - '*'

resources:
  repositories:
    - repository: self
      clean: all
      fetchDepth: 1

stages:
  - stage: Build
    displayName: 'Build and Publish'
    jobs:
      - job: BuildJob
        displayName: 'Build and publication of artifact'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - template: pipelines/build.yml
          - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/trunk') }}:
            - template: pipelines/deploy.yml